apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: admission.messenger.appscode.com
  labels:
    app: messenger
webhooks:
- name: notifier.admission.messenger.appscode.com
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/admission.messenger.appscode.com/v1alpha1/notifiers
    caBundle: ${KUBE_CA}
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - messenger.appscode.com
    apiVersions:
    - "*"
    resources:
    - notifiers
  failurePolicy: Fail
